"""DeepEval artifact code generator for ready-to-use Python code."""

import logging
from typing import List

from .models import DeepEvalMetric, EvaluationScenario, DeepEvalStrategy

logger = logging.getLogger(__name__)


class ArtifactGenerator:
    """Generates ready-to-use DeepEval Python code."""

    def generate_deepeval_code(self, strategy: DeepEvalStrategy) -> str:
        """Generate complete DeepEval evaluation code."""
        code_parts = []
        
        # Add imports
        code_parts.append(self._generate_imports(strategy))
        
        # Add metric definitions
        code_parts.append(self._generate_metrics(strategy.deepeval_metrics))
        
        # Add test case definitions
        code_parts.append(self._generate_test_cases(strategy))
        
        # Add evaluation setup
        code_parts.append(self._generate_evaluation_setup(strategy))
        
        return "\n\n".join(code_parts)

    def _generate_imports(self, strategy: DeepEvalStrategy) -> str:
        """Generate import statements."""
        imports = [
            "\"\"\"DeepEval evaluation suite generated by QA Pilot DeepEval Copilot.\"\"\"",
            "\"\"\"Issue: {strategy.issue_title}\"\"\"",
            "\"\"\"Generated on: [AUTOMATED DATE]\"\"\"",
            "",
            "from deepeval import evaluate",
            "from deepeval.test_case import ConversationalTestCase",
        ]
        
        # Add metric imports based on selected metrics
        metric_imports = set()
        for metric in strategy.deepeval_metrics:
            metric_name = metric.name.lower().replace(" ", "_")
            if metric_name == "answer_relevancy":
                metric_imports.add("from deepeval.metrics import AnswerRelevancyMetric")
            elif metric_name == "conversation_relevancy":
                metric_imports.add("from deepeval.metrics import ConversationRelevancyMetric")
            elif metric_name == "conversation_completeness":
                metric_imports.add("from deepeval.metrics import ConversationCompletenessMetric")
            elif metric_name == "faithfulness":
                metric_imports.add("from deepeval.metrics import FaithfulnessMetric")
            elif metric_name == "bias":
                metric_imports.add("from deepeval.metrics import BiasMetric")
            elif metric_name == "toxicity":
                metric_imports.add("from deepeval.metrics import ToxicityMetric")
        
        imports.extend(sorted(metric_imports))
        imports.append("")
        
        return "\n".join(imports)

    def _generate_metrics(self, metrics: List[DeepEvalMetric]) -> str:
        """Generate metric definitions."""
        if not metrics:
            return "# No metrics selected for this issue"
        
        code_lines = ["# DeepEval Metrics", ""]
        
        for metric in metrics:
            code_lines.append(f"# {metric.name}")
            code_lines.append(f"# {metric.reason}")
            code_lines.append(metric.code_snippet)
            code_lines.append("")
        
        return "\n".join(code_lines)

    def _generate_test_cases(self, strategy: DeepEvalStrategy) -> str:
        """Generate test case definitions."""
        code_lines = ["# Evaluation Test Cases", ""]
        
        # Conversational scenarios
        if strategy.conversational_scenarios:
            code_lines.append("# Conversational Scenarios")
            for i, scenario in enumerate(strategy.conversational_scenarios, 1):
                code_lines.append(f"conversational_test_case_{i} = ConversationalTestCase(")
                code_lines.append(f'    scenario="""')
                code_lines.append(f'    {scenario.scenario}')
                code_lines.append(f'    """,')
                code_lines.append(f'    expected="{scenario.expected_behavior}",')
                code_lines.append(f'    metrics=[{self._get_metric_name(scenario.metric_type)}]')
                code_lines.append(f")")
                code_lines.append("")
        
        # Prompt injection scenarios
        if strategy.prompt_injection_scenarios:
            code_lines.append("# Prompt Injection Scenarios")
            for i, scenario in enumerate(strategy.prompt_injection_scenarios, 1):
                code_lines.append(f"prompt_injection_test_case_{i} = ConversationalTestCase(")
                code_lines.append(f'    scenario="""')
                code_lines.append(f'    {scenario.scenario}')
                code_lines.append(f'    """,')
                code_lines.append(f'    expected="{scenario.expected_behavior}",')
                code_lines.append(f'    metrics=[{self._get_metric_name(scenario.metric_type)}]')
                code_lines.append(f")")
                code_lines.append("")
        
        return "\n".join(code_lines)

    def _generate_evaluation_setup(self, strategy: DeepEvalStrategy) -> str:
        """Generate evaluation setup code."""
        code_lines = ["# Evaluation Setup", ""]
        
        # Collect all test cases
        test_cases = []
        if strategy.conversational_scenarios:
            test_cases.extend([f"conversational_test_case_{i}" 
                             for i in range(1, len(strategy.conversational_scenarios) + 1)])
        if strategy.prompt_injection_scenarios:
            test_cases.extend([f"prompt_injection_test_case_{i}" 
                             for i in range(1, len(strategy.prompt_injection_scenarios) + 1)])
        
        if test_cases:
            code_lines.append("# Run evaluation")
            code_lines.append("test_cases = [" + ", ".join(test_cases) + "]")
            code_lines.append("")
            code_lines.append("# Evaluate all test cases")
            code_lines.append("results = evaluate(test_cases)")
            code_lines.append("")
            code_lines.append("# Print results")
            code_lines.append("for result in results:")
            code_lines.append("    print(f\"Test: {result.input}\")")
            code_lines.append("    print(f\"Success: {result.success}\")")
            code_lines.append("    print(f\"Score: {result.score}\")")
            code_lines.append("    print(\"---\")")
        else:
            code_lines.append("# No test cases generated for this issue")
        
        return "\n".join(code_lines)

    def _get_metric_name(self, metric_type: str) -> str:
        """Get metric variable name from metric type."""
        metric_map = {
            "Answer Relevancy": "answer_relevancy_metric",
            "Conversation Relevancy": "conversation_relevancy_metric",
            "Conversation Completeness": "conversation_completeness_metric",
            "Faithfulness": "faithfulness_metric",
            "Bias": "bias_metric",
            "Toxicity": "toxicity_metric",
            "Safety": "answer_relevancy_metric"  # Fallback for safety
        }
        return metric_map.get(metric_type, "answer_relevancy_metric")
