"""DeepEval artifact code generator for ready-to-use Python code."""

import logging

from .models import DeepEvalMetric, DeepEvalStrategy

logger = logging.getLogger(__name__)


class ArtifactGenerator:
    """Generates ready-to-use DeepEval Python code."""

    def generate_deepeval_code(self, strategy: DeepEvalStrategy) -> str:
        """Generate complete DeepEval evaluation code."""
        code_parts = []

        # Add imports
        code_parts.append(self._generate_imports(strategy))

        # Add metric definitions
        code_parts.append(self._generate_metrics(strategy.deepeval_metrics))

        # Add test case definitions
        code_parts.append(self._generate_test_cases(strategy))

        # Add evaluation setup
        code_parts.append(self._generate_evaluation_setup(strategy))

        return "\n\n".join(code_parts)

    def _generate_imports(self, strategy: DeepEvalStrategy) -> str:
        """Generate import statements for custom GEval metrics."""
        imports = [
            '"""DeepEval evaluation suite generated by QA Pilot."""',
            '"""Issue: {strategy.issue_title}"""',
            '"""Generated on: [AUTOMATED DATE]"""',
            "",
            "from deepeval import evaluate",
            "from deepeval.test_case import LLMTestCase, LLMTestCaseParams",
            "from deepeval.metrics import GEval",
        ]

        imports.append("")

        return "\n".join(imports)

    def _generate_metrics(self, metrics: list[DeepEvalMetric]) -> str:
        """Generate metric definitions."""
        if not metrics:
            return "# No metrics selected for this issue"

        code_lines = ["# DeepEval Metrics", ""]

        for metric in metrics:
            code_lines.append(f"# {metric.name}")
            code_lines.append(f"# {metric.reason}")
            code_lines.append(metric.code_snippet)
            code_lines.append("")

        return "\n".join(code_lines)

    def _generate_test_cases(self, strategy: DeepEvalStrategy) -> str:
        """Generate test case definitions using LLMTestCase for GEval metrics."""
        code_lines = ["# Evaluation Test Cases", ""]

        # Conversational scenarios
        if strategy.conversational_scenarios:
            code_lines.append("# Conversational Scenarios")
            for i, scenario in enumerate(strategy.conversational_scenarios, 1):
                code_lines.append(f"test_case_{i} = LLMTestCase(")
                code_lines.append(f'    input="{scenario.scenario}",')
                code_lines.append(
                    '    actual_output="",  # Replace with actual AI response'
                )
                code_lines.append(
                    f'    expected_output="{scenario.expected_behavior}",'
                )
                code_lines.append(")")
                code_lines.append("")

        # Prompt injection scenarios
        if strategy.prompt_injection_scenarios:
            code_lines.append("# Prompt Injection Scenarios")
            for i, scenario in enumerate(strategy.prompt_injection_scenarios, 1):
                test_num = len(strategy.conversational_scenarios) + i
                code_lines.append(f"test_case_{test_num} = LLMTestCase(")
                code_lines.append(f'    input="{scenario.scenario}",')
                code_lines.append(
                    '    actual_output="",  # Replace with actual AI response'
                )
                code_lines.append(
                    f'    expected_output="{scenario.expected_behavior}",'
                )
                code_lines.append(")")
                code_lines.append("")

        return "\n".join(code_lines)

    def _generate_evaluation_setup(self, strategy: DeepEvalStrategy) -> str:
        """Generate evaluation setup code for GEval metrics."""
        code_lines = ["# Evaluation Setup", ""]

        # Collect all test cases
        test_cases = []
        total_scenarios = len(strategy.conversational_scenarios) + len(
            strategy.prompt_injection_scenarios
        )

        if total_scenarios > 0:
            test_cases.extend([f"test_case_{i}" for i in range(1, total_scenarios + 1)])

        # Collect all metric names
        metric_names = []
        for metric in strategy.deepeval_metrics:
            # Extract metric name from code snippet (e.g., "pii_leakage_metric")
            metric_code = metric.code_snippet
            if "=" in metric_code:
                metric_name = metric_code.split("=")[0].strip()
                metric_names.append(metric_name)

        if test_cases and metric_names:
            code_lines.append("# Run evaluation with custom GEval metrics")
            code_lines.append("test_cases = [" + ", ".join(test_cases) + "]")
            code_lines.append("")
            code_lines.append("# Evaluate each test case with all relevant metrics")
            code_lines.append("for test_case in test_cases:")
            code_lines.append("    for metric in [" + ", ".join(metric_names) + "]:")
            code_lines.append("        test_case.metrics = [metric]")
            code_lines.append("        result = evaluate([test_case])")
            code_lines.append('        print(f"Test: {test_case.input}")')
            code_lines.append('        print(f"Metric: {metric.name}")')
            code_lines.append('        print(f"Success: {result[0].success}")')
            code_lines.append('        print(f"Score: {result[0].score}")')
            code_lines.append('        print("---")')
        else:
            code_lines.append("# No test cases or metrics generated for this issue")

        return "\n".join(code_lines)
